[mypy]

[mypy-cupy.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-tensorflow.*]
ignore_missing_imports = True

[mypy-mkl_fft.*]
ignore_missing_imports = True

[mypy-pyfftw.*]
ignore_missing_imports = True
